spring.application.name=project

server.port=8080
server.servlet.context-path=/
# devtools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

#-Dspring.profiles.active=dev
#spring.profiles.active=h2
#spring.profiles.active=oracle
spring.profiles.active=oracle, dev

#SQL ?? ????.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true


#- oracle ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=hyun
spring.datasource.password=tiger

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
#-spring.jpa.show-sql=true
#-spring.jpa.properties.hibernate.format_sql=true